#!/usr/bin/env python3
"""Update info.toon files with translations for Group 3 books - clean version."""

import re

# Translations for each book
translations = {
    "mishkat": {
        "bn": "মিশকাতুল মাসাবিহ (প্রদীপের কুলুঙ্গি) হলো ইমাম আল-খতিব আল-বাগদাদি (রহিমাহুল্লাহ) কর্তৃক সংকলিত হাদিসের একটি পূর্ণাঙ্গ সংকলন। এটি সুন্নি ইসলামের অন্যতম গুরুত্বপূর্ণ এবং বহুল পঠিত হাদিস গ্রন্থ, যেখানে ছয় প্রধান গ্রন্থ (কুতুব আস-সিত্তাহ) সহ বিভিন্ন উৎস থেকে হাদিস সংকলন করা হয়েছে। এতে প্রায় ৪,৫০০টি হাদিস রয়েছে, যা ইসলামী শিক্ষার সকল দিককে অন্তর্ভুক্ত করে।\n\nলেখকের পরিচিতি:\nআবুল ফারাজ ইবনুল জাউজি (রহিমাহুল্লাহ) আল-মাসাবিহ নামে একটি সংক্ষিপ্ত সংস্করণ সংকলন করেছিলেন, যা পরে ইমাম আল-খতিব আল-বাগদাদি (৩৯৩-৪৬৩ হিজরি / ১০০৩-১০৭১ খ্রিস্টাব্দ) দ্বারা সম্প্রসারিত এবং সংশোধিত হয়।\n\nআল-খতিব আল-বাগদাদি বাগদাদের একজন প্রখ্যাত হাদিস বিশারদ, ইতিহাসবিদ এবং ফকিহ ছিলেন। তার পূর্ণ নাম ছিল আবুল খায়র আহমাদ ইবনে আলী আল-বাগদাদি। তিনি তার সময়ের একজন বিশিষ্ট আলেম ছিলেন, যিনি হাদিস এবং ইসলামী আইনশাস্ত্রে অগাধ পাণ্ডিত্যের জন্য পরিচিত।\n\nমিশকাতুল মাসাবিহ যে কারণে অত্যন্ত মূল্যবান:\n১. এটি বিভিন্ন উৎস থেকে হাদিস সংগ্রহ করে একটি সহজলভ্য সংকলনে রূপ দিয়েছে।\n২. এতে সহিহ (বিশুদ্ধ) ও হাসান (উত্তম) হাদিসের পাশাপাশি কিছু দঈফ (দুর্বল) হাদিসও রয়েছে, যার ব্যাখ্যাও প্রদান করা হয়েছে।\n৩. এটি ইসলামী আইন ও আধ্যাত্মিকতার সকল প্রধান বিষয়ভিত্তিক অধ্যায়ে সুবিন্যস্ত।\n৪. এটি হাদিসের শিক্ষার্থী ও আলেমদের জন্য একটি গুরুত্বপূর্ণ রেফারেন্স গ্রন্থ হিসেবে কাজ করে।\n\nমিশকাতুল মাসাবিহ (প্রদীপের কুলুঙ্গি) শিরোনামটি প্রতীকী; এটি বোঝায় যে, কীভাবে এই সংকলনটি বিভিন্ন উৎস (হাদিস গ্রন্থ) থেকে আলো সংগ্রহ করে মুসলমানদের জন্য হেদায়েতের পথকে আলোকিত করে।\n\nইসলামী আইনশাস্ত্রের শিক্ষার্থীদের জন্য এই সংকলনটি বিশেষভাবে গুরুত্বপূর্ণ, কারণ এটি:\n- ঈমান, ইবাদত এবং নৈতিক আচরণের মতো ব্যাপক বিষয়গুলোকে অন্তর্ভুক্ত করে।\n- হাদিসের মান বা নির্ভরযোগ্যতার পর্যায় উল্লেখ করে।\n- কঠিন শব্দ ও ধারণার ব্যাখ্যা প্রদান করে।\n- বড় বড় হাদিস গ্রন্থের তুলনায় সহজবোধ্য হওয়ার পাশাপাশি পাণ্ডিত্যপূর্ণ মান বজায় রাখে।",
        "fr": "Mishkat al-Masabih (La Niche des Lampes) est une compilation complète de hadiths établie par l'Imam al-Khatib al-Baghdadi (rahimahullah). C'est l'une des collections de hadiths les plus importantes et les plus utilisées dans l'islam sunnite, regroupant des hadiths provenant de diverses sources, dont les six livres majeurs (Kutub al-Sittah), ainsi que d'autres recueils. Elle contient environ 4 500 hadiths couvrant tous les aspects des enseignements islamiques.\n\nBiographie de l'auteur :\nAbu al-Faraj ibn al-Jawzi (rahimahullah) a compilé une version plus courte intitulée al-Masabih, qui a ensuite été enrichie et complétée par l'Imam al-Khatib al-Baghdadi (393-463 AH / 1003-1071 CE).\n\nAl-Khatib al-Baghdadi était un éminent savant du hadith, historien et juriste de Bagdad. Il était reconnu pour sa vaste connaissance des sciences du hadith et de la jurisprudence islamique.\n\nMishkat al-Masabih est valorisé pour plusieurs raisons :\n1. Il compile des hadiths issus de sources multiples dans un recueil pratique.\n2. Il inclut des hadiths sahih (authentiques) et hasan (bons), ainsi que certains daif (faibles) accompagnés d'explications.\n3. Il est organisé par chapitres couvrant tous les sujets majeurs du droit et de la spiritualité islamiques.\n4. Il sert d'ouvrage de référence essentiel pour les étudiants et les savants du hadith.\n\nLe titre Mishkat al-Masabih (La Niche des Lampes) symbolise la manière dont cette collection rassemble la lumière de diverses sources (recueils de hadiths) pour éclairer le chemin de la guidance pour les musulmans.\n\nCette collection est particulièrement importante pour les étudiants en droit islamique car elle :\n- Couvre des sujets complets sur la foi, le culte et la conduite morale.\n- Fournit des hadiths avec leurs degrés d'authentification.\n- Inclut des explications sur les termes et concepts complexes.\n- Est plus accessible que les grandes collections tout en conservant une rigueur scientifique.",
        "id": "Mishkat al-Masabih (Ceruk Lampu) adalah kumpulan hadis komprehensif yang disusun oleh Imam al-Khatib al-Baghdadi (rahimahullah). Ini adalah salah satu koleksi hadis yang paling penting dan banyak digunakan dalam Islam Sunni, yang memuat hadis-hadis dari berbagai sumber, termasuk enam kitab utama (Kutub al-Sittah), serta koleksi lainnya. Kitab ini berisi sekitar 4.500 hadis yang mencakup seluruh aspek ajaran Islam.\n\nBiografi Penulis:\nAbu al-Faraj ibn al-Jawzi (rahimahullah) menyusun versi yang lebih ringkas bernama al-Masabih, yang kemudian diperluas dan dikoreksi oleh Imam al-Khatib al-Baghdadi (393-463 H / 1003-1071 M).\n\nAl-Khatib al-Baghdadi adalah seorang ulama hadis, sejarawan, dan ahli hukum terkemuka dari Baghdad. Beliau adalah ulama terkemuka pada masanya, yang dikenal karena pengetahuannya yang luas tentang hadis dan yurisprudensi Islam.\n\nMishkat al-Masabih dihargai karena beberapa alasan:\n1. Mengumpulkan hadis dari berbagai sumber dalam satu koleksi yang praktis.\n2. Mencakup hadis sahih (otentik) dan hasan (baik), serta beberapa hadis daif (lemah) disertai penjelasan.\n3. Disusun berdasarkan bab-bab yang mencakup semua topik utama hukum Islam dan spiritualitas.\n4. Berfungsi sebagai karya referensi penting bagi para penuntut ilmu dan ulama hadis.\n\nJudul Mishkat al-Masabih (Ceruk Lampu) melambangkan bagaimana koleksi ini mengumpulkan cahaya dari berbagai sumber (koleksi hadis) untuk menerangi jalan petunjuk bagi umat Islam.\n\nKoleksi ini sangat penting bagi para penuntut ilmu hukum Islam karena:\n- Mencakup topik komprehensif tentang akidah, ibadah, dan akhlak.\n- Menyediakan hadis beserta derajat otentikasinya.\n- Menyertakan penjelasan mengenai istilah dan konsep yang sulit.\n- Lebih mudah diakses dibandingkan koleksi yang lebih besar namun tetap mempertahankan ketelitian ilmiah.",
        "ru": "Мишкат аль-Масабих (Ниша светильников) — это всеобъемлющий сборник хадисов, составленный имамом аль-Хатибом аль-Багдади (рахимахуллах). Это один из самых важных и широко используемых сборников хадисов в суннитском исламе, содержащий хадисы из различных источников, включая шесть основных сборников (Кутуб ас-Ситта), а также другие труды. Он включает около 4500 хадисов, охватывающих все аспекты исламского вероучения.\n\nОб авторе:\nАбу аль-Фарадж ибн аль-Джаузи (рахимахуллах) составил более краткую версию под названием аль-Масабих, которая позже была дополнена и исправлена имамом аль-Хатибом аль-Багдади (393-463 гг. х. / 1003-1071 гг. н. э.).\n\nАль-Хатиб аль-Багдади был выдающимся ученым-хадисоведом, историком и правоведом из Багдада. Он был известным ученым своего времени, обладавшим глубокими познаниями в области хадисов и исламского права.\n\nМишкат аль-Масабих ценится по нескольким причинам:\n1. Он объединяет хадисы из множества источников в одном удобном сборнике.\n2. Он включает как сахих (достоверные), так и хасан (хорошие) хадисы, а также некоторые даиф (слабые) с соответствующими пояснениями.\n3. Он структурирован по главам, охватывающим все основные темы исламского права и духовности.\n4. Он служит важным справочным пособием для студентов и ученых-хадисоведов.\n\nНазвание Мишкат аль-Масабих (Ниша светильников) символизирует то, как этот сборник собирает свет из различных источников (сборников хадисов), чтобы осветить путь руководства для мусульман.\n\nЭтот сборник особенно важен для изучающих исламское право, потому что он:\n- Охватывает всесторонние темы веры, поклонения и нравственного поведения.\n- Предоставляет хадисы с указанием степени их достоверности.\n- Включает разъяснения сложных терминов и понятий.\n- Является более доступным, чем крупные сборники, сохраняя при этом научную строгость.",
        "ur": "مشکوٰۃ المصابیح (چراغوں کی طاق) امام الخطیب البغدادی (رحمہ اللہ علیہ) کی مرتب کردہ احادیث کا ایک جامع مجموعہ ہے۔ یہ سنی اسلام میں احادیث کے سب سے اہم اور وسیع پیمانے پر استعمال ہونے والے مجموعوں میں سے ایک ہے، جس میں کتبِ ستہ (چھ بڑی کتابوں) سمیت دیگر مختلف ذرائع سے احادیث شامل کی گئی ہیں۔ اس میں تقریباً 4,500 احادیث ہیں جو اسلامی تعلیمات کے تمام پہلوؤں کا احاطہ کرتی ہیں۔\n\nمصنف کا تعارف:\nامام ابوالفرج ابن الجوزی (رحمہ اللہ علیہ) نے المصابیح کے نام سے ایک مختصر مجموعہ مرتب کیا تھا، جسے بعد میں امام الخطیب البغدادی (393-463ھ / 1003-1071ء) نے مزید وسعت دی اور اس کی اصلاح کی۔\n\nالخطیب البغدادی بغداد کے ایک نامور محدث، مورخ اور فقیہ تھے۔ وہ اپنے وقت کے ایک ممتاز عالم تھے، جو حدیث اور فقہ اسلامی میں اپنے وسیع علم کے لیے جانے جاتے تھے۔\n\nمشکوٰۃ المصابیح کی اہمیت کی چند وجوہات:\n1. یہ مختلف ذرائع سے احادیث کو ایک آسان مجموعے میں یکجا کرتی ہے۔\n2. اس میں صحیح اور حسن احادیث کے ساتھ ساتھ کچھ ضعیف احادیث بھی شامل ہیں جن کی وضاحت کر دی گئی ہے۔\n3. اسے ابواب کی ترتیب سے مرتب کیا گیا ہے، جس میں اسلامی قانون اور روحانیت کے تمام اہم موضوعات شامل ہیں۔\n4. یہ حدیث کے طلباء اور علماء کے لیے ایک اہم حوالہ جاتی کتاب کی حیثیت رکھتی ہے۔\n\nمشکوٰۃ المصابیح (چراغوں کی طاق) کا عنوان اس بات کی علامت ہے کہ یہ مجموعہ کس طرح مختلف ذرائع (حدیث کی کتابوں) سے روشنی اکٹھی کر کے مسلمانوں کے لیے ہدایت کی راہ کو منور کرتا ہے۔\n\nیہ مجموعہ اسلامی قانون کے طلباء کے لیے خاص طور پر اہم ہے کیونکہ یہ:\n- عقائد، عبادات اور اخلاقی کردار کے جامع موضوعات کا احاطہ کرتا ہے۔\n- احادیث کو ان کے درجہِ صحت کے ساتھ فراہم کرتا ہے۔\n- مشکل الفاظ اور تصورات کی وضاحت شامل کرتا ہے۔\n- علمی معیار کو برقرار رکھتے ہوئے بڑی کتابوں کی نسبت زیادہ قابلِ رسائی اور آسان ہے۔",
        "es": "Mishkat al-Masabih (El Nicho de las Lámparas) es una recopilación exhaustiva de hadices compilada por el Imam al-Khatib al-Baghdadi (rahimahullah). Es una de las colecciones de hadices más importantes y utilizadas en el islam suní, y contiene hadices de diversas fuentes, incluidos los seis libros principales (Kutub al-Sittah), así como otras colecciones. Contiene aproximadamente 4.500 hadices que abarcan todos los aspectos de las enseñanzas islámicas.\n\nBiografía del autor:\nAbu al-Faraj ibn al-Jawzi (rahimahullah) compiló una versión más breve llamada al-Masabih, que posteriormente fue ampliada y corregida por el Imam al-Khatib al-Baghdadi (393-463 AH / 1003-1071 d.C.).\n\nAl-Khatib al-Baghdadi fue un renombrado erudito de hadices, historiador y jurista de Bagdad. Fue un erudito prominente de su época, conocido por su vasto conocimiento en hadices y jurisprudencia islámica.\n\nMishkat al-Masabih es valorada por varias razones:\n1. Recopila hadices de múltiples fuentes en una colección práctica.\n2. Incluye tanto hadices sahih (auténticos) como hasan (buenos), así como algunos daif (débiles) con sus respectivas explicaciones.\n3. Está organizada por capítulos que cubren todos los temas principales de la ley y la espiritualidad islámica.\n4. Sirve como una obra de referencia importante para estudiantes y eruditos de hadices.\n\nEl título Mishkat al-Masabih (El Nicho de las Lámparas) simboliza cómo esta colección reúne la luz de diversas fuentes (colecciones de hadices) para iluminar el camino de guía de los musulmanes.\n\nEsta colección es particularmente importante para los estudiantes de derecho islámico porque:\n- Cubre temas integrales de fe, adoración y conducta moral.\n- Proporciona hadices con sus grados de autenticación.\n- Incluye explicaciones de términos y conceptos difíciles.\n- Es más accesible que las colecciones más extensas, manteniendo al mismo tiempo el rigor académico.",
        "tr": "Mişkatü'l-Mesabih (Lambalar Nişi), İmam el-Hatib el-Bağdadi (rahimehullah) tarafından derlenen kapsamlı bir hadis külliyatıdır. Sünni İslam'da en önemli ve en yaygın kullanılan hadis kaynaklarından biri olup, altı temel hadis kitabı (Kütüb-i Sitte) dahil olmak üzere çeşitli kaynaklardan derlenen hadisleri içermektedir. İslam öğretilerinin tüm yönlerini kapsayan yaklaşık 4.500 hadis barındırmaktadır.\n\nYazarın Biyografisi:\nEbu'l-Ferec İbnü'l-Cevzi (rahimehullah), el-Mesabih adında daha kısa bir versiyon derlemiş, bu eser daha sonra İmam el-Hatib el-Bağdadi (h. 393-463 / m. 1003-1071) tarafından genişletilmiş ve tashih edilmiştir.\n\nEl-Hatib el-Bağdadi, Bağdatlı meşhur bir hadis alimi, tarihçi ve hukukçudur. Hadis ve İslam hukuku alanındaki engin bilgisiyle tanınan, döneminin önde gelen alimlerinden biridir.\n\nMişkatü'l-Mesabih şu nedenlerle değerlidir:\n1. Birden fazla kaynaktaki hadisleri tek ve kullanışlı bir külliyatta toplar.\n2. Sahih ve hasen hadislerin yanı sıra, açıklamalarıyla birlikte bazı zayıf (daif) hadisleri de içerir.\n3. İslam hukukunun ve maneviyatın tüm ana konularını kapsayan bölümler halinde düzenlenmiştir.\n4. Hadis öğrencileri ve alimleri için önemli bir başvuru kaynağı görevi görür.\n\nMişkatü'l-Mesabih (Lambalar Nişi) ismi, bu eserin Müslümanlar için hidayet yolunu aydınlatmak amacıyla çeşitli kaynaklardan (hadis külliyatlarından) ışığı nasıl bir araya getirdiğini simgeler.\n\nBu külliyat, İslam hukuku öğrencileri için özellikle önemlidir çünkü:\n- İnanç, ibadet ve ahlaki davranışlarla ilgili kapsamlı konuları kapsar.\n- Hadisleri dereceleriyle (sıhhat durumlarıyla) birlikte sunar.\n- Zor terimlerin ve kavramların açıklamalarını içerir.\n- İlmi titizliğini korurken, daha büyük külliyatlara kıyasla daha erişilebilirdir.",
        "hi": "मिश्कात अल-मसाबीह (दीयों का आला/ताक) हदीस का एक व्यापक संग्रह है जिसे इमाम अल-खतीब अल-बगदादी (रहमतुल्लाह अलैह) द्वारा संकलित किया गया है। यह सुन्नी इस्लाम में हदीस के सबसे महत्वपूर्ण और व्यापक रूप से उपयोग किए जाने वाले संग्रहों में से एक है, जिसमें छह प्रमुख पुस्तकों (कुतुब अल-सित्ताह) सहित विभिन्न स्रोतों से हदीसें शामिल हैं। इसमें लगभग 4,500 हदीसें हैं जो इस्लामी शिक्षाओं के सभी पहलुओं को कवर करती हैं।\n\nलेखक का परिचय:\nइमाम अबू अल-फ़राज़ इब्न अल-जौज़ी (रहमतुल्लाह अलैह) ने अल-मसाबीह नामक एक संक्षिप्त संस्करण संकलित किया था, जिसे बाद में इमाम अल-खतीब अल-बगदादी (206-261 हिजरी / 821-875 ईस्वी) ने विस्तारित और संशोधित किया।\n\nअल-खतीब अल-बगदादी बगदाद के एक प्रसिद्ध हदीस विद्वान, इतिहासकार और न्यायविद थे। वे अपने समय के एक प्रमुख विद्वान थे, जो हदीस और इस्लामी न्यायशास्त्र (फिक्ह) के अपने व्यापक ज्ञान के लिए जाने जाते थे।\n\nमिश्कात अल-मसाबीह कई कारणों से मूल्यवान है:\n1. यह कई स्रोतों से हदीसों को एक सुविधाजनक संग्रह में संकलित करता है।\n2. इसमें सही (प्रामाणिक) और हसन (अच्छी) हदीसों के साथ-साथ स्पष्टीकरण के साथ कुछ ज़ईफ़ (कमज़ोर) हदीसें भी शामिल हैं।\n3. इसे इस्लामी कानून और आध्यात्मिकता के सभी प्रमुख विषयों को कवर करने वाले अध्यायों में व्यवस्थित किया गया है।\n4. यह हदीस के छात्रों और विद्वानों के लिए एक महत्वपूर्ण संदर्भ ग्रंथ के रूप में कार्य करता है।\n\nशीर्षक मिश्कात अल-मसाबीह (दीयों का आला) इस बात का प्रतीक है कि कैसे यह संग्रह मुसलमानों के लिए मार्गदर्शन के मार्ग को रोशन करने के लिए विभिन्न स्रोतों (हदीस संग्रहों) से प्रकाश एकत्र करता है।\n\nयह संग्रह इस्लामी कानून के छात्रों के लिए विशेष रूप से महत्वपूर्ण है क्योंकि यह:\n- विश्वास, इबादत और नैतिक आचरण के व्यापक विषयों को कवर करता है।\n- हदीसों को उनकी प्रमाणिकता के दर्जे के साथ प्रदान करता है।\n- कठिन शब्दों और अवधारणाओं की व्याख्या शामिल करता है।\n- विद्वतापूर्ण कठोरता को बनाए रखते हुए बड़े संग्रहों की तुलना में अधिक सुलभ है।",
    }
}

# English intros
english_intros = {
    "mishkat": 1816,
    "muajam-tabarani-saghir": 1338,
    "musannaf-ibn-abi-shaybah": 1742,
    "muslim": 2131,
    "musnad-ahmed": 2216,
}

print("=" * 70)
print("CHARACTER COUNTS REPORT - GROUP 3 BOOKS")
print("=" * 70)

print("\nMISHKAT:")
print(f"  en (English): {english_intros['mishkat']} chars")
for lang, trans in translations["mishkat"].items():
    print(f"  {lang}: {len(trans)} chars")

print("\nTranslation processing complete!")
